<form id="itra-insurance-form" action="">
    <fieldset>
        <ul class="form-list">
            <li id="insurance-form">
                <fieldset>
                    <ul>
                        <li class="wide">
                            <label for="insurance" class="required"><em>*</em><?php echo $this->__('Do you want to arrange insuranceMethod?') ?></label>
                            <div class="input-box">
                                <select class="required-entry" name="insurance" id="insurance">
                                    <option value=''><?php echo $this->__('Please Choose..');?></option>
                                    <option value='1'><?php echo $this->__('Yes');?></option>
                                    <option value='2'><?php echo $this->__('No');?></option>
                                </select>
                            </div>
                        </li>
                    </ul>
                </fieldset>
            </li>
        </ul>
        <div id="insurance-message" hidden>Cost of insurance is <span id="cost"></span></div>
        <div class="buttons-set" id="insurance-buttons-container">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="insuranceMethod.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <span class="please-wait" id="insurance-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
    //<![CDATA[
    var insuranceMethod = new InsuranceMethod('itra-insurance-form','<?php echo $this->getUrl('insurance/onepage/saveInsurance') ?>');
    var insuranceForm = new VarienForm('itra-insurance-form');
    //]]>
</script>
<script src="<?php echo $this->getSkinUrl('js/stepinsurance.js'); ?>"></script>