<div class="block block-progress opc-block-progress">
    <div class="block-title">
        <strong><span><?php echo $this->__('Your Checkout Progress') ?></span></strong>
    </div>
    <div class="block-content">
        <dl>
            <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
            <div id="billing-progress-opcheckout">
                <?php echo $this->getChildHtml('billing.progress') ?>
            </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
            <div id="shipping-progress-opcheckout">
                <?php echo $this->getChildHtml('shipping.progress') ?>
            </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
            <div id="shipping_method-progress-opcheckout">
                <?php echo $this->getChildHtml('shippingmethod.progress') ?>
            </div>
            <?php endif; ?>

            <?php if (Mage::helper('insurance')->isEnabled() && $this->getCheckout()->getStepData('insurance', 'is_show')): ?>
                <?php if($this->getCheckout()->getStepData('insurance', 'complete')): ?>
                    <dt class="complete">
                        <?php echo $this->__('Insurance Review') ?> <span class="separator">|</span> <a href="#insurance" onclick="checkout.accordion.openSection('opc-insurance'); return false;"><?php echo $this->__('Change') ?></a>
                    </dt>
                    <dd class="complete">
                        <div>
                            <?php echo $this->__('Insurance Review Is: ');?>
                            <?php
                            $cost = $this->getQuote()->getInsuranceAmount();
                            if($cost){
                                echo 'The cost of insurance was ' . $cost;
                            } else{
                                echo $this->__('No');
                            }
                            ?>
                        </div>
                    </dd>
                <?php else: ?>
                    <dt>
                        <?php echo $this->__('Insurance Review') ?>
                    </dt>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
            <div id="payment-progress-opcheckout">
                <?php echo $this->getChildHtml('payment.progress') ?>
            </div>
            <?php endif; ?>
        </dl>
    </div>
</div>

