<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load">
       <!-- Content loaded dynamically -->
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
    //]]>
        var cost = "<?php echo Mage::helper('insurance')->getCostInsurance(); ?>";
    </script>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <?php if(Mage::helper('insurance')->isEnabled()): ?>
    <fieldset>
        <ul class="form-list">
            <li id="insurance-form">
                <fieldset>
                    <ul>
                        <li class="wide">
                            <label for="insurance" class="required"><em>*</em><?php echo $this->__('Do you want to arrange insurance?') ?></label>
                            <div class="input-box">
                                <select class="required-entry" name="insurance" id="insurance">
                                    <option value=''><?php echo $this->__('Please Choose..');?></option>
                                    <option value='1'><?php echo $this->__('Yes');?></option>
                                    <option value='2'><?php echo $this->__('No');?></option>
                                </select>
                            </div>
                        </li>
                    </ul>
                </fieldset>
            </li>
        </ul>
    </fieldset>
    <div id="insurance-message" hidden>Cost of insurance is <span id="cost"></span></div>
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <?php endif ?>
    <div class="buttons-set" id="shipping-method-buttons-container">

        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" onclick="shippingMethod.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>
<script src="<?php echo $this->getSkinUrl('js/stepinsurance.js'); ?>"></script>